title: Sai Sudeep Das
description: PhD Scholar @ IIT Delhi | Computational Linguistics | Syntax, Phonetics & Odia NLP
author: Sai Sudeep Das
email: huz258337@iitd.ac.in

# Theme
theme: minima
plugins:
  - jekyll-feed

# Custom CSS - Force Jekyll to use our stylesheet
sass:
  sass_dir: _sass
  style: compressed
